### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by colinramsay** [payloadcms/plugin-search#2]
This is a bit of a long shot as I'm not sure whether it's an issue with my setup or not. I'm using https://github.com/payloadcms/remix-server and everything is working was expected, but now I've added `plugin-search` I see the following when running `pnpm run dev`.

I'd appreciate any pointers!

```
@org/server:dev: /mnt/data/projects/remix/node_modules/.pnpm/payload@1.1.4_pcrzm5c6sygikws7dntnespqza/node_modules/payload/components/forms.ts:1
@org/server:dev: export {
@org/server:dev: ^^^^^^
@org/server:dev: 
@org/server:dev: SyntaxError: Unexpected token 'export'
@org/server:dev:     at Object.compileFunction (node:vm:352:18)
@org/server:dev:     at wrapSafe (node:internal/modules/cjs/loader:1032:15)
@org/server:dev:     at Module._compile (node:internal/modules/cjs/loader:1067:27)
@org/server:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
@org/server:dev:     at Object.require.extensions.<computed> [as .ts] (/mnt/data/projects/remix/node_modules/.pnpm/ts-node@10.9.1_i7crlymf22c7hnawxb4tbubvdq/node_modules/ts-node/src/index.ts:1608:43)
@org/server:dev:     at Module.load (node:internal/modules/cjs/loader:981:32)
@org/server:dev:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@org/server:dev:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@org/server:dev:     at require (node:internal/modules/cjs/helpers:102:18)
@org/server:dev:     at Object.<anonymous> (/mnt/data/projects/remix/node_modules/.pnpm/@payloadcms+plugin-search@1.0.0_payload@1.1.4/node_modules/@payloadcms/plugin-search/src/Search/ui/index.tsx:2:1)
```

**Comment by jacobsfletch** [comment]
@colinramsay that error is likely related to your setup trying to import the module which is written in ES6 syntax, but your environment doesn't support it. You might need to adjust your settings to transpile ES6 modules to CommonJS, Babel is a common solution for this. I am not personally versed in Remix to know how they handle this.

**Comment by colinramsay** [comment]
The thing is that everything else works fine until the search plugin comes into play. I'm gonna close this though as I think you're right that it's a problem with my set up. Thanks for replying!
