### ISSUE TITLE
Importing using Yarn results in Webpack error

### ISSUE THREAD

**Issue by rafaeldatarock** [payloadcms/plugin-search#3]
**Downloading the source files from this repo and importing locally works fine!**

To reproduce:
- Setup Payload CMS (I'm using TypeScript)
- `yarn add @payloadcms/plugin-search`
- Import search from '@payloadcms/plugin-search'
- Add search to payload's plugin config
- `yarn dev`
- Open admin panel in browser

![image](https://user-images.githubusercontent.com/43268243/211503553-3b812d9a-6aa1-48ae-b6f2-82967104fb78.png)

**Comment by jacobsfletch** [comment]
Hey @rafaeldatarock are you still experiencing this issue? Try bumping your plugin to the latest version and let me know how it goes.

**Comment by rafaeldatarock** [comment]
I haven't worked with Payload for a while, will check soon and let you know.

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-search) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. Please refer to [this open discussion](https://github.com/payloadcms/payload/discussions/4496) for more details and to continue the conversation. Or feel free to [open a new discussion](https://github.com/payloadcms/payload/discussions) around this, or even [hop on our Discord](https://discord.com/invite/payload) and get help there.
